variable "vpc_name" {}
variable "vpc_cidr" {}
variable "igw_name" {}
variable "public_cird1" {}
variable "public_subnet1" {}
variable "public_cidr2" {}
variable "public_subnet2" {}
variable "private_cidr1" {}
variable "private_subnet1" {}
variable "private_cidr2" {}
variable "private_subnet2" {}
variable "DB_CIDR1" {}
variable "DB_SUBNET1" {}
variable "DB_CIDR2" {}
variable "DB_SUBNET2" {}
variable "EIP_NAME1" {}
variable "EIP_NAME2" {}
variable "NGW_NAME1" {}
variable "NGW_NAME2" {}
variable "PUBLIC_RT_NAME" {}
variable "PRIVATE_RT_NAME1" {}
variable "PRIVATE_RT_NAME2" {}
variable "DB_RT_NAME1" {}
variable "DB_RT_NAME2" {}