variable "vpc_name" {}
variable "vpc_cidr" {}
variable "igw_name" {}
variable "public_cird1" {}
variable "public_subnet1" {}
variable "public_cidr2" {}
variable "public_subnet2" {}
variable "private_cidr1" {}
variable "private_subnet1" {}
variable "private_cidr2" {}
variable "private_subnet2" {}
variable "db_cird1" {}
variable "db_subnet1" {}
variable "db_cird2" {}
variable "db_subnet2" {}
variable "eip_name1" {}
variable "eip_name2" {}
variable "ngw_name1" {}
variable "ngw_name2" {}
variable "public_routeTable_name" {}
variable "private_routeTable_name1" {}
variable "private_routeTable_name2" {}
variable "db_routeTable_name1" {}
variable "db_routeTable_name2" {}