variable "public_subnet_name1" {}
variable "public_subnet_name2" {}
variable "private_subnet_name1" {}
variable "private_subnet_name2" {}
variable "web_elb_securityGroup_name" {}
variable "app_elb_securityGroup_name" {}
variable "web_elb_name" {}
variable "app_elb_name" {}
variable "web_tg_name" {}
variable "app_tg_name" {}
variable "vpc_name" {}
variable "web_elb_securityGroup_id" {}
variable "app_elb_securityGroup_id" {}
variable "header_name" {}
variable "header_value" {}