variable "ami_name" {}
variable "launch-template-name" {}
variable "web-sg-name" {}
variable "app-sg-name" {}
variable "private-subnet-name1" {}
variable "private-subnet-name2" {}
variable "instance-profile-name" {}
variable "web-asg-name" {}
variable "app-asg-name" {}
variable "web-sg-id" {}
variable "app-sg-id" {}
variable "web-tg-arn" {}
variable "app-tg-arn" {}
variable "ami-id" {}
variable "app-alb-dns-name" {}