variable "ami-id" {}
variable "ami_name" {}
variable "webTier_securityGroup_name" {}
variable "appTier_securityGroup_name" {}
variable "private_subnet_name1" {}
variable "private_subnet_name2" {}
variable "instance_profile_name" {}
variable "web_asg_name" {}
variable "app_asg_name" {}
variable "web-securityGroup-id" {}
variable "app-securityGroup-id" {}
variable "web-targetGroup-arn" {}
variable "app-targetGroup-arn" {}
variable "app_alb_dns_name" {}
