variable "sg-name" {}
variable "db-subnet-name1" {}
variable "db-subnet-name2" {}
variable "DB_SG_NAME" {}
variable "rds-username" {}
variable "rds-pwd" {}
variable "db-name" {}
variable "rds-name" {}
variable "db-instance-class" {}
variable "db-sg-id" {}
variable "db-user-id" {}
variable "db-user-pwd" {}