variable "db_securityGroup_name" {}
variable "db_subnet_name1" {}
variable "db_subnet_name2" {}
variable "dbTier_securityGroup_name" {}
variable "rds_username" {}
variable "rds_pwd" {}
variable "db_name" {}
variable "rds_name" {}
variable "db_securityGroup_id" {}
variable "db_user_id" {}
variable "db_user_pwd" {}