variable "public-subnet-name1" {}
variable "public-subnet-name2" {}
variable "private-subnet-name1" {}
variable "private-subnet-name2" {}
variable "WEB_ALB_SG_NAME" {}
variable "APP_ALB_SG_NAME" {}
variable "web-alb-name" {}
variable "app-alb-name" {}
variable "web-tg-name" {}
variable "app-tg-name" {}
variable "vpc_name" {}
variable "web-alb-sg-id" {}
variable "app-alb-sg-id" {}
variable "header-name" {}
variable "header-value" {}